server:
  port: 8181

spring:
  profiles: docker
  application.name: spring-mysql-docker
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysql_test
    username: root
    password: root
