---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: spring-mysql-docker
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql-docker
  labels:
    app: web
spec:
  containers:
    - name: mysql
      image: test-mysql-docker:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
    - name: web
      image: web-spring:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8181
